baseURL = "https://rur.pages.dev/"
languageCode = "en-us"
title = "rur"

disableKinds = ["RSS", "sitemap", "taxonomy", "term"]

[minify]
  disableXML = true
  toml = true
  tojson = true
  tocss = true
  tohtml = true

  [minify.tdewolff.html]
    keepWhitespace = false
    keepComments = false
    keepDocumentTags = false
    keepConditionalComments = false

  [minify.tdewolff.css]
    keepCSS2 = false

  [minify.tdewolff.js]
    mangle = true
