baseURL = "https://rur.pages.dev/"
languageCode = "en-us"
title = "rur"

disableKinds = ["RSS", "sitemap", "taxonomy", "taxonomyTerm"]

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
